## Tianyi Zhang 9598110243

### 1. Setting up an Integrated Development Environment (IDE)

### 2. Google Colab

### 3. Pandas

In [72]:
import pandas as pd

In [73]:
# data3b = pd.read_csv('Salaries.csv')  

In [74]:
data3c = pd.read_csv('Salaries.csv', index_col = 3, header=0, skiprows=range(1, 2))

print(data3c.index)
print(data3c.columns)
# print(data3c.iloc[0])

print(data3c.head(5))

Index(['bedrost01', 'benedbr01', 'campri01', 'ceronri01', 'chambch01',
       'dedmoje01', 'forstte01', 'garbege01', 'harpete01', 'hornebo01',
       ...
       'stammcr01', 'storedr01', 'strasst01', 'taylomi02', 'thornma01',
       'treinbl01', 'ugglada01', 'werthja01', 'zimmejo02', 'zimmery01'],
      dtype='object', name='playerID', length=25574)
Index(['yearID', 'teamID', 'lgID', 'salary'], dtype='object')
           yearID teamID lgID  salary
playerID                             
bedrost01    1985    ATL   NL  550000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000


In [75]:
data3d = data3c[data3c.teamID == ('ATL' or 'HOU')]

print(data3d.shape)
data3d = data3d[data3d.salary > 1000000]

print(data3d.shape)
print(data3d.head(5))

(885, 4)
(325, 4)
           yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
hornebo01    1986    ATL   NL  1800000
murphda05    1986    ATL   NL  1825000


In [76]:
data3e = data3c[data3c.teamID == 'ATL']

data3e.describe()

yearID        salary
count   885.000000  8.850000e+02
mean   1999.725424  2.207749e+06
std       8.766470  3.434320e+06
min    1985.000000  6.000000e+04
25%    1992.000000  3.000000e+05
50%    1999.000000  6.000000e+05
75%    2007.000000  2.400000e+06
max    2015.000000  1.606180e+07

In [80]:
# print(data3c.shape)
for index, data in data3c.iterrows():
    data3f['yearID'].append(data[0])
    data3f['teamID'].append(data[1])
    data3f['lgID'].append(data[2])
    data3f['salary'].append(data[3])
# print(data[0], data[1], data[2], data[3])

print(data3f.keys())
print(len(data3f['salary']))


data3F = data3c.to_dict('list')

dict_keys(['yearID', 'teamID', 'lgID', 'salary'])
485906


In [83]:
data3g = pd.DataFrame(data = data3F)
data3g.columns = ['a', 'b', 'c', 'd']

print(data3g.head(5))

      a    b   c       d
0  1985  ATL  NL  550000
1  1985  ATL  NL  545000
2  1985  ATL  NL  633333
3  1985  ATL  NL  625000
4  1985  ATL  NL  800000


### 4. Numpy

In [85]:
import numpy as np

In [87]:
data4a = np.array([[1, 2], [3, 4]])

In [101]:
print(data4a)
print('ndim:',data4a.ndim, '\nshape:',data4a.shape, '\ndtype:', data4a.dtype, '\nitemsize:', data4a.itemsize)

[[1 2]
 [3 4]]
ndim: 2 
shape: (2, 2) 
dtype: int32 
itemsize: 4


In [103]:
data4c = np.reshape(data4a, (4, 1))
print(data4c)

data4c = data4c.flatten()
print(data4c)

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [106]:
data4d = data4a[1]
print(data4d)

data4d = data4a[:]
print(data4d)

[3 4]
[[1 2]
 [3 4]]


In [124]:
print(np.argmin(data4a))

print(np.argmax(data4a))

print(np.min(data4a, axis = 0))
print(np.min(data4a))

print(np.max(data4a, axis = 1))
print(np.max(data4a))

print(np.mean(data4a))
print(np.sum(data4a))
print(np.std(data4a))

print(np.dot(data4a, data4d))
print(np.mod(data4a, data4d))

print(np.square(data4a))
print(np.sqrt(data4a))
print(np.abs(data4a))
print(np.exp(data4a))
print(np.sign(data4a))

0
3
[1 2]
1
[2 4]
4
2.5
10
1.118033988749895
[[ 7 10]
 [15 22]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 2]
 [3 4]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1 1]
 [1 1]]


In [139]:
data4f = np.arange(2, 12, 2)
print(data4f)

data4f = np.ones((3, 4))
print(data4f)

data4f = np.zeros((4, 3)).reshape(2, 6)
print(data4f)

data4f = np.eye(4)
print(data4f)

data4f = np.linspace(1, 14, 12).reshape(6, 2)
print(data4f)

data1 = np.array([[1, 0, 1], [4, 2, 2]])
data2 = np.array([[3, 4, 4], [1, 2, 2]])
data4f = np.concatenate([data1, data2], axis = 1)
print(data4f)

[ 2  4  6  8 10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.          2.18181818]
 [ 3.36363636  4.54545455]
 [ 5.72727273  6.90909091]
 [ 8.09090909  9.27272727]
 [10.45454545 11.63636364]
 [12.81818182 14.        ]]
[[1 0 1 3 4 4]
 [4 2 2 1 2 2]]


### 5. Scikit-Learn

### 6. Git and GitHub

### 7. Matplotlib

### 8. Seaborn